### ISSUE TITLE
Bug in the json.decoder

### ISSUE THREAD

**Issue by Zerbaib** [Zerbaib/MotDePassePy#8]
```
Traceback (most recent call last):
  File "/home/hugo/Documents/github/Zerbaib/MotDePassePy/main.py", line 30, in <module>
    list = json.load(file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 37 (char 36)
```
The last commit at this working is ``fa7f8bb`` and i don't know why i have this bug at the **start** of the prog

**Comment by Zerbaib** [comment]
I changed my .txt file to .json
it worked
then when I tried to put the os module to do this:
```os.system("clear")```
at the start of the while
I had the bug at the time
so I removed the os module and all the lines that go with it
and i still have the bug
